services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
#      - gunicorn
#      - mysite.wsgi:application
#      - --bind
#      - "0.0.0.0:8000"

    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200"
    volumes:
      - ./mysite/database:/app/database
#      - ./mysite/staticfiles:/app/staticfiles

