# Generated by Django 5.2.1 on 2025-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="orders/receipts/"),
        ),
    ]
